### PR TITLE
Week 3

### PR DESCRIPTION
**Pull request by ypke**

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
Please, clean your directories in a way to remove output files, empty files,  temp. files and everything what shouldn't be with .sh files. You can leave .sql and .csv as they are part of the scripts.

Check, if you have all the scripts and all the screenshots.

**Comment by ypke** [comment]
> 

Thanks @borisbradic i updated the pr. i just copied all files from the server and pushed them. i  checked one more time, I hope all scripts and screenshots are there

**Review by borisbradic — CHANGES_REQUESTED** [review]
Check directory chapter16 > test11.sh is it a script or output file? 

Please, try to put screenshots in directories named by the chapter: "chapter13",  "chapter14", etc.. like this I can't navigate.. thank you.

**Comment by ypke** [comment]
> Check directory chapter16 > test11.sh is it a script or output file?
> 
> Please, try to put screenshots in directories named by the chapter: "chapter13", "chapter14", etc.. like this I can't navigate.. thank you.

Yeah, you are right, it is not a script it is the output that I created by mistake. I have one question before I push the changes. The examples start after test10.sh script in chapter 16 page 435, in the book we run the test11.sh/test12.sh scripts but there are no examples of script content, I suppose it is the same as test10.sh (that part confused me)?

**Comment by borisbradic** [comment]
Yes, you can go without those, it will be okey.

**Review by borisbradic — APPROVED** [review]
I will approve this now.

**Comment by ypke** [comment]
> 

Thank you @borisbradic

**Pull request merged**
